# Generated by Django 3.2.7 on 2021-10-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_testmodel_fakemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakemodel',
            name='last_modified_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
