# Generated by Django 3.2.7 on 2021-11-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_fakemodel_last_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakemodel',
            name='json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
